# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddbc81f253599977b0b297ead6de7b87e04db4ed3a535d1261a782f16618bbd5fe094ad5f8ebd3b1c0c9cf67a0877658981318456933cb56e0800fb61c09a48d

test:
  secret_key_base: dd2f5db951c0ddfed7815c62a6b0f330d3de1a2ef387afce9624a282843d50e130d602f567eb0d30de3b5aa1fbc79f52ee348bf69fc37e2e25e94cac17257b20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
